import $primary from '../../settings/styles/DefaultPrimarySettings';

let $_ = {
  loginOptionBackgroundColor: $primary.secondaryColor,
  loginOptionBorderColor: $primary.secondaryColor,
  loginPageBackgroundColor: $primary.primaryColor,
  loginOptionPaddingTop: $primary.baseGridUnit * 3,
  loginLabelColor: $primary.interfaceColors._3,
  loginLabelPaddingTop: $primary.baseGridUnit * 3,
  loginLabelPaddingBottom: $primary.baseGridUnit * 2,
  loginLabelPaddingleft: $primary.baseGridUnit * 2,
  loginLabelHeight: $primary.baseGridUnit * 6,
  loginBackgroundColor: $primary.interfaceColors._6,
//   loginInputFieldsContainerMarginBottom: $primary.baseGridUnit * 4,
  loginInputFieldsContainerMarginBottomAndroid: $primary.baseGridUnit * 0.8,
  loginLabelFontSize: $primary.baseFontSize,
  loginLabelFontfamily: $primary.fontFamilyAndroid.regular,
  loginLabelFontfamilyIOS: $primary.fontFamily.medium,
//   loginforgotPasswordLinkMarginTop: $primary.baseGridUnit,
//   loginforgotPasswordLinkMarginRight: $primary.baseGridUnit * 2,
//   privacyPolicyContainerPadding: $primary.baseGridUnit * 7,
//   privacyPolicyTextFontSize: $primary.baseFontSize,
//   containerHeaderColor: $primary.interfaceColors._3,
//   registerlabelColor: $primary.primaryColor,
//   registerlabelFontSize: $primary.baseFontSize + 2

// Testing, Delete after use
    productName: $primary.productName,
    toclogo: 'toclogo',
    toclogoColor: 'white',
    headerBackgroundColor: $primary.primaryColor,
    headerPaddingTop: $primary.baseGridUnit * 4,
    headerPaddingBottom: $primary.baseGridUnit + 10,
    searchFieldsBackgroundColor: $primary.primaryColor,
    searchFieldsPadding: $primary.baseGridUnit * 2 ,
    headerTitleColor: $primary.white,
    searchBoxPlaceholderColor: $primary.white,
    switchIconColor: $primary.white,
    switchIconSize: $primary.baseGridUnit * 4,
    searchBoxTextInputViewPaddingHorizontal: $primary.baseGridUnit,
    searchBoxTextInputColor: $primary.white,
    searchBoxTextInputHeight: $primary.baseGridUnit * 5,
    cancelBorderColor: $primary.secondaryColor,
    actionsWrapperBorderTopColor: $primary.interfaceColors._5,
    actionsWrapperBackgroundColor: $primary.white,
    searchBoxBorderColor: 'transparent',
    searchBoxBorderWidth: 0,
    searchBoxPlaceholderFontSize: $primary.baseFontSize + 4,
    searchBoxTextInputFontSize: $primary.baseFontSize + 10,
    searchScrollViewBackgroundColor: $primary.interfaceColors._6,
    PassengersAndRailCardsModalWrapperMarginBottom: $primary.baseGridUnit * 2,
    searchScrollViewMargin: $primary.baseGridUnit * 2,
    carnetTermsAndConditionFontSize: $primary.baseFontSize + 1,
    carnetTermsAndConditionColor: $primary.interfaceColors._3,
    newTicketTypeBoxTextColor: $primary.interfaceColors._2,
    newTicketTypeContainerBorderColor: $primary.interfaceColors._4,
};

export default $_;