export default constants = {
    ACTIONS: {
        SAVE_GUEST_DATA: 'SAVE_GUEST_DATA',
        UPDATE_COMPETENCY_LEVEL: 'UPDATE_COMPETENCY_LEVEL',
        UPDATE_VIRTUAL_COMPETENCY_LEVEL: 'UPDATE_VIRTUAL_COMPETENCY_LEVEL',
        SAVE_LOGGEDIN_USER_DATA: 'SAVE_LOGGEDIN_USER_DATA',
        UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
        LOGIN_GENERAL_ERROR: 'LOGIN_GENERAL_ERROR',
        SHOW_SPINNER_MODAL: 'SHOW_SPINNER_MODAL',
        RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
        CLEAR_DATA: 'CLEAR_DATA'
    }
}