export default constants = {
    ACTIONS: {
        UPDATE_QUIZ_LIST: 'UPDATE_QUIZ_LIST',
        CLEAR_DATA: 'CLEAR_DATA',
        CLEAR_ERRORS: 'CLEAR_ERRORS',
        CLEAR_SCHEDULE: 'CLEAR_SCHEDULE',
        GENERAL_ERROR_ATTENDANCE: 'GENERAL_ERROR_ATTENDANCE',
        UPDATE_SEQUENCE: 'UPDATE_SEQUENCE',
        UPDATE_CURRENT_QUIZ: 'UPDATE_CURRENT_QUIZ',
        GENERAL_ERROR_QUIZLIST: 'GENERAL_ERROR_QUIZLIST',
        UPDATE_OPPONENT_SCORE: 'UPDATE_OPPONENT_SCORE'
    }
}