import $primary from '../../settings/styles/DefaultPrimarySettings';

let $_ = {
    buttonPaddingTop: $primary.baseGridUnit + 10,
    buttonPaddingBottom: $primary.baseGridUnit+ 10,
    buttonPaddingTopAndroid: $primary.baseGridUnit + 10,
    buttonPaddingBottomAndroid: $primary.baseGridUnit + 10,
    buttonSecondaryPaddingTop: $primary.baseGridUnit + 10,
    buttonSecondaryPaddingBottom: $primary.baseGridUnit + 10,
    buttonSecondaryPaddingTopAndroid: $primary.baseGridUnit + 10,
    buttonSecondaryPaddingBottomAndroid: $primary.baseGridUnit + 10,
    buttonWrapperMargin: $primary.baseGridUnit*2,
    buttonPrimaryBackgroundColor: $primary.secondaryColor,
    buttonQuaternaryBackgroundColor: $primary.tertiaryColor,
    buttonQuaternaryShadowColor: '#8695A2',
    buttonQuaternaryColor: $primary.interfaceColors._2,
    buttonPrimaryColor: $primary.white,
    buttonPrimaryShadowColor: $primary.secondaryColor,
    buttonPrimaryDisabled: $primary.disabledColor,
    buttonPrimaryFontSize: $primary.baseFontSize+4,
    buttonPrimaryFontWeightAndroid: $primary.fontFamilyAndroid.regular,
    buttonPrimaryFontFamilyIOS: $primary.fontFamily.medium,
    buttonSecondaryBackgroundColor: $primary.white,
    buttonSecondaryColor: $primary.secondaryColor,
    buttonSecondaryShadowColor: $primary.interfaceColors._5,
    buttonSecondaryBorderColor: $primary.secondaryColor,
    buttonTertiaryWrapperWidth: $primary.baseGridUnit*30,
    buttonTertiaryBorderColor: $primary.opacityVarients.black16,
    buttonTertiaryBackgroundColor: $primary.white,
    buttonTertiaryColor: $primary.interfaceColors._2,
    buttonTertiaryPaddingTop: $primary.baseGridUnit-1,
    buttonTertiaryPaddingBottom: $primary.baseGridUnit - 1.5,
    buttonTertiaryPaddingAndroid: $primary.baseGridUnit - 0.5,
    buttonTertiaryFontSize: $primary.baseFontSize,
    buttonTertiaryTextFontWeightAndroid: $primary.fontFamilyAndroid.medium,
    buttonTertiaryTextFontFamilyIOS: $primary.fontFamily.bold,
    buttonShadowWidth: $primary.baseGridUnit-5,
    flatButtonColor: $primary.secondaryColor,
    flatButtonPadding: $primary.baseGridUnit,
    flatButtonFontSize: $primary.baseFontSize + 8,
    floatingButtonBackgroundColor: $primary.primaryColor,
    floatingButtonShadowColor: $primary.black,
};

export default $_;
