export default constants = {
    ACTIONS: {
        UPDATE_OPPONENT_SCORE: 'UPDATE_OPPONENT_SCORE',
        CLAER_OPPONENT_SCORE: 'CLAER_QUIZ_OPTION',
        CLEAR_DATA: 'CLEAR_DATA',
        GENERAL_ERROR_FETCH_SCORE: 'GENERAL_ERROR_FETCH_SCORE'
    },

}