export default constants ={
    ACTIONS:{
        SAVE_LEADERSBOARD_DATA: 'SAVE_LEADERSBOARD_DATA',
        CLEAR_DATA: 'CLEAR_DATA',
        CLEAR_LEADERSBOARD_DATA: 'CLEAR_LEADERSBOARD_DATA',
        UPDATE_SCORE: 'UPDATE_SCORE',

    }
}