export default constants = {
    ACTIONS: {
        UPDATE_SCHEDULE_LEADERBOARD: 'UPDATE_SCHEDULE_LEADERBOARD',
        UPDATE_SCHEDULE_LEADERBOARD_FINAL: 'UPDATE_SCHEDULE_LEADERBOARD_FINAL',
        CLEAR_DATA: 'CLEAR_DATA',
        CLEAR_ERRORS: 'CLEAR_ERRORS',
        GENERAL_ERROR_LEADERBOARD: 'GENERAL_ERROR_LEADERBOARD',
        CLEAR_SCHEDULE_LEADERBOARD: 'CLEAR_SCHEDULE_LEADERBOARD',
    }
}