export default constants = {
    ACTIONS: {
        UPDATE_SCHEDULE_LEADERBOARD: 'UPDATE_SCHEDULE_LEADERBOARD',
        CLEAR_DATA: 'CLEAR_DATA',
        GENERAL_ERROR_LEADERBOARD: 'GENERAL_ERROR_LEADERBOARD',
        CLEAR_SCHEDULE_LEADERBOARD: 'CLEAR_SCHEDULE_LEADERBOARD',
        GENERAL_ERROR_ATTENDANCE: 'GENERAL_ERROR_ATTENDANCE',
        CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE'
    }
}